### ISSUE TITLE
FAIL. Reason: call did not revert as expected

### ISSUE THREAD

**Issue by Jaunepr** [Cyfrin/path-solidity-developer-2023#1175]
### Lesson

Lesson 7

### Operating System

Windows

### Describe the bug

i don't know why it's didn't revert!
here is part of test code:
```
contract FundMeTest is Test {
    // constructor() {

    // }
    FundMe fundMe;
    address SENDER = makeAddr("jaunepr");
    uint256 constant SEND_VALUE = 1 ether;
    uint256 constant SENDER_BALANCE = 10 ether;

    // uint256 constant FUNDERS_INDEX = 0;

    function setUp() external {
        DeployFundMe deployFundMe = new DeployFundMe();
        fundMe = deployFundMe.run();
        vm.deal(SENDER, SENDER_BALANCE);
    }
    modifier funded() {
        vm.prank(SENDER);
        fundMe.Fund{value: SEND_VALUE}();
        _;
    }

    function testOnlyOwnerCanWithdraw() public funded {
        vm.prank(SENDER);
        vm.expectRevert();
        fundMe.Withdraw();
    }
```
and i use forge test --match-test testOnlyOwnerCanWithdraw -vvv
then, here is ouput:
```
[FAIL. Reason: call did not revert as expected] testOnlyOwnerCanWithdraw() (gas: 108176)
Traces:
  [108176] FundMeTest::testOnlyOwnerCanWithdraw()
    ├─ [0] VM::prank(jaunepr: [0xD32aC66b047b3Ba085a452E26814BD4F20A99929])
    │   └─ ← ()
    ├─ [81354] FundMe::Fund{value: 1000000000000000000}()
    │   ├─ [8993] MockV3Aggregator::latestRoundData() [staticcall]
    │   │   └─ ← 1, 200000000000 [2e11], 1, 1, 1
    │   └─ ← ()
    ├─ [0] VM::prank(jaunepr: [0xD32aC66b047b3Ba085a452E26814BD4F20A99929])
    │   └─ ← ()
    ├─ [0] VM::expectRevert(custom error f4844814:)
    │   └─ ← ()
    ├─ [6788] FundMe::Withdraw()
    │   ├─ [0] jaunepr::fallback{value: 1000000000000000000}()
    │   │   └─ ← ()
    │   └─ ← ()
    └─ ← call did not revert as expected

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 1.75ms
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/FundMeTest.t.sol:FundMeTest
[FAIL. Reason: call did not revert as expected] testOnlyOwnerCanWithdraw() (gas: 108176)

Encountered a total of 1 failing tests, 0 tests succeeded

**Comment by Winter9998** [comment]
### Hi!

Ensure that the `Withdraw` function has a condition that checks for ownership and correctly reverts if the caller is not the owner. for example from OpenZeppelin the `Ownable` contract which includes the `onlyOwner` modifier. 
You should try also to add parenthesis () here to `funded` : ` function testOnlyOwnerCanWithdraw() public funded <- {`.

**Comment by Jaunepr** [comment]
I've tried adding parentheses () but still have the same problem
and i checked owner and sender are different address.

**Comment by Winter9998** [comment]
Ok could you tell me why `vm.expectRevert();` is above ` fundMe.Withdraw();` ? If you want it to revert itself you should put it below at the bottom not first

**Comment by Jaunepr** [comment]
```vm.expectRevert();``` means Asserts that the next call reverts.
And I want to test the wrong call, so I prank an address that isn't owner to withdraw, then the wrong call would cause revert.  So I put ```vm.expectRevert();``` above ```fundMe.Withdraw();```  to make the test pass. 
Am I understanding right?

**Comment by Winter9998** [comment]
Yes my bad I forgot how was working expectRevert() . Could you paste your original contract ?

**Comment by Jaunepr** [comment]
I solved it by remove the  vm.prank(SENDER); 
```
function testOnlyOwnerCanWithdraw() public funded {
        // vm.prank(SENDER);
        vm.expectRevert();
        fundMe.Withdraw();
    }
```
but i don't know the reason.  i got two call, so i use two prank. doesn't prank() means next once call? can you explain it ?
